{% set name = "ib-insync" %}
{% set nameUnderscore = "ib_insync" %}
{% set version = "0.9.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ nameUnderscore[0] }}/{{ nameUnderscore }}/{{ nameUnderscore }}-{{ version }}.tar.gz
  sha256: b218c602dc9844c1d867448d14d29f12caa66657f56c48f0e96165b2edd07672

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - flake8
  run:
    - python >=3.6
    - eventkit
    - nest-asyncio

test:
  imports:
    - ib_insync

about:
  home: https://github.com/erdewit/ib_insync
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python sync/async framework for Interactive Brokers API
  description: |
    The goal of the IB-insync library is to make working with the Trader Workstation API from Interactive Brokers as easy as possible.
    The main features are
    * An easy to use linear style of programming;
    * An IB component that automatically keeps in sync with the TWS or IB Gateway application;
    * A fully asynchonous framework based on asyncio and eventkit for advanced users;
    * Interactive operation with live data in Jupyter notebooks.
  doc_url: https://ib-insync.readthedocs.io/api.html
  dev_url: https://github.com/erdewit/ib_insync

extra:
  recipe-maintainers:
    - yehoshuadimarsky
