travis:
  secure:
    BINSTAR_TOKEN: S8SOp94PYT623sw1/Y06YdDN9bUKLKspPjUwCNoKAJYYhCb54dEbq4jh/hwnBtYlFV8+kOuSErarlGRfYXACHHsanLgtUcyZ4o96/OKUFVjXra17wWlH09iptfZc2zVQzHdPCh7vgDZI/3Sbm2ynlZYO7gLy5fLPblx9A7JYHtrklXdkFoPrpEky0LRxOYYHSL+z8XSX+1wkksX7SwryKYyHuot3fkytHBdM14ylrK93ud2NfZb8DJM/lt3jFt4LOTSX2Wf+lV29qxmdBHmthGNrDrWUwEKDxh5AGDgXv6wi1Lble2xGIh0dog8lnFoboFuwrqDVHL2CQ4o9fhLDQSdxwBw9vpNwy+1VaBynU8hz2Mltn1Emg7A8CExtpR9pG69zrgWFJkE06ey9O61MeyhwOUaCAzMnee8Rkqhi1HrUJ6HxOUZ63ANvBwsneBGjth8M3hc3lcFtJb9ln6ItMflrAB0BZ+h+PXqhSLEndzrXZZuGViyQQLG20FX0fZoHCzAAuaYYNN56yqOdF3PvPZJayo/PLiQQxAC+QmNT4QqSQaeDwt5g9ZjXpElY3LoXpRoJtzGocn05x9Q3D8lXboBzJrsf8mUKKtYrOv9Rpjp+F5MdyqmEiUCSVmdVgBKRUUe8PAECfaLiHUUcG+LG2WJvsGNNEOJ/h9O7kq2b7Ds=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
